name: dotdart
description: Dot file manager written in dart.
version: 0.1.0
# homepage: https://todo

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  ansicolor: ^1.1.1

dev_dependencies:
  pedantic: ^1.9.0
