#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PS1="\[$(tput bold)\]\[\e[31m\]λ\[\e[m\]\[$(tput bold)\]\[\e[32m\].\[\e[m\]\[$(tput bold)\]\[\e[34m\]\h\[\e[m\] \[$(tput bold)\]\[\e[36m\]\w\[\e[m\] "

export PATH="$PATH:$HOME/flutter/bin:$HOME/bin:$HOME/flbar/build/linux/release/bundle"
export XSECURELOCK_FONT="Fira Code"

alias ls='ls --color=auto'
alias i3lock='i3lock -c 2E3440'

export MOZ_X11_EGL=1
