#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width          2
bspc config window_gap            32
bspc config top_padding 	  32

bspc config split_ratio           0.50
bspc config single_monocle        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color   \#81a1c1
bspc config focused_border_color  \#bf616a
bspc config active_border_color   \#bf616a
bspc config presel_feedback_color \#bf616a

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord state=pseudo_tiled
bspc rule -a Steam state=pseudo_tiled
